export enum CompanyType {
  PRODUCER = 'PRODUCER',
  RESTAURANT = 'RESTAURANT',
  BAR = 'BAR',
  EDITORIAL = 'EDITORIAL',
  GENERAL = 'GENERAL',
  EDUCATION = 'EDUCATION',
  BAKERY = 'BAKERY',
  CAFE = 'CAFE',
  EVENTS = 'EVENTS',
}
