export enum SectionPreset {
  HALF_SCREEN_IMAGE_TITLE_SUB_BYLINE = 'HALF_SCREEN_IMAGE_TITLE_SUB_BYLINE',
  FULL_SCREEN_IMAGE_TITLE_SUB_BYLINE = 'FULL_SCREEN_IMAGE_TITLE_SUB_BYLINE',
  INLINE_IMAGE_TITLE_SUB_BYLINE = 'INLINE_IMAGE_TITLE_SUB_BYLINE',
}
