export enum ContentType {
  ISSUE = 'ISSUE',
  EXTRACT = 'EXTRACT',
  HEADING = 'HEADING',
  SUB_HEADING = 'SUB_HEADING',
  LEAD = 'LEAD',
  PARAGRAPH = 'PARAGRAPH',
  TITLE = 'TITLE',
  BYLINE = 'BYLINE',
  IMAGE = 'IMAGE',
}
